### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-dataverse-teams.2-provision-environment 
title: Provision your first Dataverse environment
metadata: 
  title: Provision your first Dataverse environment 
  description: Learn how to provision your first Dataverse environment. 
  ms.date: 03/23/2022
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 3 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-provision-environment.md)] 
